version: '3.3'

volumes:
  mongodb_data:
  mysql_data:

services:
  mongo:
    image: mongo
    volumes:
      - './mongodb_data:/data/db'
    ports:
      - "27017:27017"

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - './mysql_data:/var/lib/mysql '
    ports:
      - "3306:3306"
